name: Checkout and Upload Artifacts

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: checkout-artifact  # Change to a descriptive name for your artifact
        path: ${{ github.workspace }}/src/  # Use the current working directory as the path
