name: Checkout and Upload Artifacts

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Rename folders
      run: |
        mkdir test
        ls -lrt
        cp -r src/main test/
        cp -r src/test test/
        cd test/main
        ls -lrt
      working-directory: ${{ github.workspace }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trip-artifact  # Change tname for your artifact
        path: ${{ github.workspace }}/test/  # get current working directory as the path
