name: Checkout and Upload Artifacts

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: list
      run: ls -lrt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trip-artifact  # Change tname for your artifact
        path: ${{ github.workspace }}/src/  # get current working directory as the path
    
    - name: Upload Folders2
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          ${{ github.workspace }}/main
          ${{ github.workspace }}/jenkins
