name: Checkout and Upload Artifacts

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Rename folders
      run: |
        mkdir test
        cp -r .github test/
        cp src test/
      working-directory: ${{ github.workspace }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trip-artifact  # Change tname for your artifact
        path: ${{ github.workspace }}/test/  # get current working directory as the path
    
    - name: Upload Folders2
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
          ${{ github.workspace }}/main
          ${{ github.workspace }}/jenkins
