name: Checkout and Upload Artifacts

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Build Number
      run: echo ${{ github.run_number }}
    - name: Rename folders
      run: |
        mkdir test
        ls -lrt
        cp -r src/main test/
        cp -r src/test test/
        cd test/main
        ls -lrt
      working-directory: ${{ github.workspace }}
    - name: Allure run
      run: |
       npm install -g allure-commandline
       allure --version
       allure generate allure-results --clean -o allure-report
       pwd
       ls -lrt
       cd ${{ github.workspace }}/allure-report/
       ls -lrt
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trip-artifact  # Change tname for your artifact
        path: ${{ github.workspace }}/allure-report/  # get current working directory as the path
